#setup vard
hostname_fqdn: "mx1.hulst010.nl"
admin_user: "pc2a"
admin_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFM+9vb2qGYkANQgyLmdVvnXLtHdd3dmTc/c3bsJ3BhR9NPdiTtu/2mdG3ESkIpCyNBxzAGpjUZnJxgsAdKfCge2RRgsJIW6mEEMnOJpL8bvKnCC0FwYjwu2agwb+Twfs/1J/5JBdfIKQbv6DI0n5ChyqEfjbdbdHT5/ytN97Jc4xjXEpy4ACCU24KeTHXVJqCsFs9yG0NjokJdfLzEXJBmTRazuYddCQnsfrRKljm7U3Q2NalA4AX2+njcr/3jkv8IJ4AqW2pwLJdw5kfAtzBW6FSApaQyBOq6hu/FVOqGt8F4wIjCUKD5OQOYh+FA592ozy5X1gDhxxncFhkGtpX rsa-key-20250804"
ssh_port: 22

# certbot vars
letsencrypt_email: "pc2a@xs4all.nl"
certbot_domains:
  - "hulst010.nl"
#  - "www.hulst010.nl"
ip4: "5.215.181.68" 
 
# default site content
web_root: "/var/www/hulst010"

# MariaDB
mariadb_packages:
  - mariadb-server
mariadb_service_name: mariadb

# MariaDB hardening (mysql_secure_installation equivalent)
mariadb_hardening: true
mariadb_root_login: "root"
mariadb_root_host: "localhost"

# In MariaDB op Debian is unix_socket auth gebruikelijk.
# Zet dit op true om root via unix_socket te forceren.
mariadb_use_unix_socket_auth: true

# Admin user maiadb
mariadb_user: "pc2a"
mariadb_password: "pi-cc1993"
mariadb_host: "localhost"

# phpMyAdmin
phpmyadmin_path: "/phpmyadmin"
phpmyadmin_allowed_ips:
  - "86.82.11.229"   
